/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOutbox,
  IOutboxInterface,
} from "../../../contracts/Market.sol/IOutbox";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "_recipientAddress",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_messageBody",
        type: "bytes",
      },
    ],
    name: "dispatch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOutbox__factory {
  static readonly abi = _abi;
  static createInterface(): IOutboxInterface {
    return new utils.Interface(_abi) as IOutboxInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOutbox {
    return new Contract(address, _abi, signerOrProvider) as IOutbox;
  }
}
