/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPUSHCommInterface,
  IPUSHCommInterfaceInterface,
} from "../../../contracts/Market.sol/IPUSHCommInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_channel",
        type: "address",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_identity",
        type: "bytes",
      },
    ],
    name: "sendNotification",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPUSHCommInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IPUSHCommInterfaceInterface {
    return new utils.Interface(_abi) as IPUSHCommInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPUSHCommInterface {
    return new Contract(address, _abi, signerOrProvider) as IPUSHCommInterface;
  }
}
