/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MarketInterface extends utils.Interface {
  functions: {
    "buy(uint32,address,address,uint256,address,uint32)": FunctionFragment;
    "buyWithERC20(uint32,address,address,uint256,address,uint32,uint256)": FunctionFragment;
    "cancelListing(address,uint256)": FunctionFragment;
    "currencyIdToChainlinkContract(uint32)": FunctionFragment;
    "currencyIdToCurrencyContractAddress(uint32)": FunctionFragment;
    "domainToContractAddress(uint32)": FunctionFragment;
    "getChainlinkContractAddress(uint32)": FunctionFragment;
    "getListInformation(uint32,address,uint256)": FunctionFragment;
    "getResisteredContract(uint32)": FunctionFragment;
    "handle(uint32,bytes32,bytes)": FunctionFragment;
    "list(address,uint256,uint256,uint32,uint32,address)": FunctionFragment;
    "listedCurrency(bytes32)": FunctionFragment;
    "listedPrice(bytes32)": FunctionFragment;
    "outbox()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "selfDomainId()": FunctionFragment;
    "sellerAddress(bytes32)": FunctionFragment;
    "setChainlinkContract(uint32,address)": FunctionFragment;
    "setContract(uint32,address)": FunctionFragment;
    "setCurrencyContractAddress(uint32,address)": FunctionFragment;
    "setSelfDomainId(uint32)": FunctionFragment;
    "testGetPriceMultiple(uint32,address,uint256,address,uint32,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buy"
      | "buyWithERC20"
      | "cancelListing"
      | "currencyIdToChainlinkContract"
      | "currencyIdToCurrencyContractAddress"
      | "domainToContractAddress"
      | "getChainlinkContractAddress"
      | "getListInformation"
      | "getResisteredContract"
      | "handle"
      | "list"
      | "listedCurrency"
      | "listedPrice"
      | "outbox"
      | "owner"
      | "renounceOwnership"
      | "selfDomainId"
      | "sellerAddress"
      | "setChainlinkContract"
      | "setContract"
      | "setCurrencyContractAddress"
      | "setSelfDomainId"
      | "testGetPriceMultiple"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buy",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithERC20",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyIdToChainlinkContract",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyIdToCurrencyContractAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "domainToContractAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainlinkContractAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getListInformation",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getResisteredContract",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "handle",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "list",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "listedCurrency",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "listedPrice",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "outbox", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selfDomainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellerAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkContract",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setContract",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrencyContractAddress",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSelfDomainId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetPriceMultiple",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyWithERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyIdToChainlinkContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyIdToCurrencyContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainToContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainlinkContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListInformation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResisteredContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "handle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listedCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "outbox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfDomainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrencyContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSelfDomainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetPriceMultiple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Bought(address,uint256,address,uint256)": EventFragment;
    "Listed(address,uint256,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Bought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Listed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface BoughtEventObject {
  nftContractAddress: string;
  tokenId: BigNumber;
  seller: string;
  price: BigNumber;
}
export type BoughtEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  BoughtEventObject
>;

export type BoughtEventFilter = TypedEventFilter<BoughtEvent>;

export interface ListedEventObject {
  nftContractAddress: string;
  tokenId: BigNumber;
  seller: string;
  price: BigNumber;
}
export type ListedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  ListedEventObject
>;

export type ListedEventFilter = TypedEventFilter<ListedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Market extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buy(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyWithERC20(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      sendPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelListing(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currencyIdToChainlinkContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    currencyIdToCurrencyContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    domainToContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getChainlinkContractAddress(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getListInformation(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, number]>;

    getResisteredContract(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    handle(
      _origin: PromiseOrValue<BigNumberish>,
      _sender: PromiseOrValue<BytesLike>,
      _messageBody: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    list(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      currencyId: PromiseOrValue<BigNumberish>,
      domainIdTo: PromiseOrValue<BigNumberish>,
      ourContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    listedCurrency(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    listedPrice(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    outbox(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    selfDomainId(overrides?: CallOverrides): Promise<[number]>;

    sellerAddress(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setChainlinkContract(
      currencyId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setContract(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCurrencyContractAddress(
      currencyId: PromiseOrValue<BigNumberish>,
      currencyContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSelfDomainId(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testGetPriceMultiple(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      msgValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buy(
    domainId: PromiseOrValue<BigNumberish>,
    contractAddress: PromiseOrValue<string>,
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    seller: PromiseOrValue<string>,
    currencyId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyWithERC20(
    domainId: PromiseOrValue<BigNumberish>,
    contractAddress: PromiseOrValue<string>,
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    seller: PromiseOrValue<string>,
    currencyId: PromiseOrValue<BigNumberish>,
    sendPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelListing(
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currencyIdToChainlinkContract(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  currencyIdToCurrencyContractAddress(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  domainToContractAddress(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getChainlinkContractAddress(
    domainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getListInformation(
    domainId: PromiseOrValue<BigNumberish>,
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, number]>;

  getResisteredContract(
    domainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  handle(
    _origin: PromiseOrValue<BigNumberish>,
    _sender: PromiseOrValue<BytesLike>,
    _messageBody: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  list(
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    currencyId: PromiseOrValue<BigNumberish>,
    domainIdTo: PromiseOrValue<BigNumberish>,
    ourContractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  listedCurrency(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<number>;

  listedPrice(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  outbox(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  selfDomainId(overrides?: CallOverrides): Promise<number>;

  sellerAddress(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  setChainlinkContract(
    currencyId: PromiseOrValue<BigNumberish>,
    contractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setContract(
    domainId: PromiseOrValue<BigNumberish>,
    contractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCurrencyContractAddress(
    currencyId: PromiseOrValue<BigNumberish>,
    currencyContractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSelfDomainId(
    domainId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testGetPriceMultiple(
    domainId: PromiseOrValue<BigNumberish>,
    nftContractAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    seller: PromiseOrValue<string>,
    currencyId: PromiseOrValue<BigNumberish>,
    msgValue: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buy(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyWithERC20(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      sendPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelListing(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    currencyIdToChainlinkContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    currencyIdToCurrencyContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    domainToContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getChainlinkContractAddress(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getListInformation(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, number]>;

    getResisteredContract(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    handle(
      _origin: PromiseOrValue<BigNumberish>,
      _sender: PromiseOrValue<BytesLike>,
      _messageBody: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    list(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      currencyId: PromiseOrValue<BigNumberish>,
      domainIdTo: PromiseOrValue<BigNumberish>,
      ourContractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    listedCurrency(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    listedPrice(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    outbox(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    selfDomainId(overrides?: CallOverrides): Promise<number>;

    sellerAddress(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setChainlinkContract(
      currencyId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setContract(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setCurrencyContractAddress(
      currencyId: PromiseOrValue<BigNumberish>,
      currencyContractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSelfDomainId(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    testGetPriceMultiple(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      msgValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Bought(address,uint256,address,uint256)"(
      nftContractAddress?: null,
      tokenId?: null,
      seller?: null,
      price?: null
    ): BoughtEventFilter;
    Bought(
      nftContractAddress?: null,
      tokenId?: null,
      seller?: null,
      price?: null
    ): BoughtEventFilter;

    "Listed(address,uint256,address,uint256)"(
      nftContractAddress?: null,
      tokenId?: null,
      seller?: null,
      price?: null
    ): ListedEventFilter;
    Listed(
      nftContractAddress?: null,
      tokenId?: null,
      seller?: null,
      price?: null
    ): ListedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    buy(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyWithERC20(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      sendPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelListing(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currencyIdToChainlinkContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currencyIdToCurrencyContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    domainToContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainlinkContractAddress(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getListInformation(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResisteredContract(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handle(
      _origin: PromiseOrValue<BigNumberish>,
      _sender: PromiseOrValue<BytesLike>,
      _messageBody: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    list(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      currencyId: PromiseOrValue<BigNumberish>,
      domainIdTo: PromiseOrValue<BigNumberish>,
      ourContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    listedCurrency(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listedPrice(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    outbox(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    selfDomainId(overrides?: CallOverrides): Promise<BigNumber>;

    sellerAddress(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setChainlinkContract(
      currencyId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setContract(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCurrencyContractAddress(
      currencyId: PromiseOrValue<BigNumberish>,
      currencyContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSelfDomainId(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testGetPriceMultiple(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      msgValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buy(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyWithERC20(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      sendPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelListing(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currencyIdToChainlinkContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currencyIdToCurrencyContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    domainToContractAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainlinkContractAddress(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getListInformation(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResisteredContract(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handle(
      _origin: PromiseOrValue<BigNumberish>,
      _sender: PromiseOrValue<BytesLike>,
      _messageBody: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    list(
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      currencyId: PromiseOrValue<BigNumberish>,
      domainIdTo: PromiseOrValue<BigNumberish>,
      ourContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    listedCurrency(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listedPrice(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    outbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    selfDomainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellerAddress(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setChainlinkContract(
      currencyId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setContract(
      domainId: PromiseOrValue<BigNumberish>,
      contractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCurrencyContractAddress(
      currencyId: PromiseOrValue<BigNumberish>,
      currencyContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSelfDomainId(
      domainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testGetPriceMultiple(
      domainId: PromiseOrValue<BigNumberish>,
      nftContractAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      seller: PromiseOrValue<string>,
      currencyId: PromiseOrValue<BigNumberish>,
      msgValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
